project:
  type: website
  output-dir: _site

website:
  title: "Partition Theory"
  navbar:
    right:
      - icon: github
        href: https://github.com/de-Manzanares/partition-theory
        aria-label: GitHub
  favicon: favicon.ico

theme:
    light: flatly
    dark: darkly

format:
  html: default