project:
  type: website
  output-dir: _site
  resources:
    - pdf/examples.pdf
    - pdf/examples-dark.pdf
    - pdf/notes.pdf
    - pdf/notes-dark.pdf

website:
  title: "Partition Theory"
  navbar:
    background: "#120023"
    foreground: "#aaaaaa"
    right:
      - icon: github
        href: https://github.com/de-Manzanares/partition-theory
        aria-label: GitHub
  favicon: favicon.ico

format:
  html:
    theme:
      dark: cyborg
      light: darkly
    mainfont: Latin Modern Roman