project:
  type: website
  output-dir: _site

website:
  title: "Partition Theory"
  navbar:
    left:
      - href: index.qmd
      - text: ""

theme:
    light: flatly
    dark: darkly

format:
  html: default