name: Publish Quarto site

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX PDFs (1)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            examples.tex
            examples-dark.tex
          working_directory: examples
          latexmk_use_lualatex: true

      - name: Compile LaTeX PDFs (2)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            notes.tex
            notes-dark.tex
          working_directory: notes
          latexmk_use_lualatex: true

      - name: Copy PDFs
        run: |
          mkdir pdf
          cp examples/*.pdf pdf/
          cp notes/*.pdf pdf/

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Render
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}