name: Publish Quarto site

on:
  push:
    branches:
      - master
    paths:
      - "*.qmd"
      - "**/*.qmd"
      - "_quarto.yml"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Render
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}